import * as cdk from "aws-cdk-lib";
import { NagSuppressions } from "cdk-nag";
import {
  CodePipeline,
  CodePipelineSource,
  ShellStep,
} from "aws-cdk-lib/pipelines";
import type { Construct } from "constructs";
import type { EnvironmentConfig } from "../../config/types";
import { AppStage } from "../stages/app-stage";

export interface PipelineStackProps extends cdk.StackProps {
  readonly devConfig: EnvironmentConfig;
  readonly prodConfig: EnvironmentConfig;
}

export class PipelineStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: PipelineStackProps) {
    super(scope, id, props);

    const source = CodePipelineSource.connection(
      props.devConfig.githubRepo,
      props.devConfig.githubBranch,
      {
        connectionArn: props.devConfig.codestarConnectionArn,
      },
    );

    const pipeline = new CodePipeline(this, "Pipeline", {
      pipelineType: cdk.aws_codepipeline.PipelineType.V2,
      selfMutation: true,
      synth: new ShellStep("Synth", {
        input: source,
        installCommands: [
          "n 22",
          "npm install -g pnpm",
        ],
        commands: [
          "pnpm install --frozen-lockfile",
          "pnpm run build",
          "pnpm run test",
          "cd infra && npx cdk synth",
        ],
        primaryOutputDirectory: "infra/cdk.out",
      }),
    });

    // CDK Pipelines generates internal resources (artifacts bucket, CodeBuild
    // projects, IAM roles) that we cannot configure directly. Suppress cdk-nag
    // findings for these managed resources.
    NagSuppressions.addStackSuppressions(this, [
      {
        id: "AwsSolutions-S1",
        reason:
          "Pipeline artifacts bucket is CDK-managed; access logging not required for CI/CD artifacts",
      },
      {
        id: "AwsSolutions-CB4",
        reason:
          "CodeBuild projects are CDK Pipelines-managed; KMS encryption not required for CI/CD build artifacts",
      },
      {
        id: "AwsSolutions-IAM5",
        reason:
          "Wildcard permissions are generated by CDK Pipelines for internal artifact bucket and CodeBuild log access",
      },
    ]);

    // Dev stage — auto-deploy
    const devStage = new AppStage(this, "Dev", {
      env: props.devConfig.env,
      config: props.devConfig,
    });

    pipeline.addStage(devStage);

    // Prod stage — auto-deploy
    const prodStage = new AppStage(this, "Prod", {
      env: props.prodConfig.env,
      config: props.prodConfig,
    });

    pipeline.addStage(prodStage);
  }
}
